"""empty message

Revision ID: b137cd5b718d
Revises: 
Create Date: 2022-11-24 17:41:49.550619

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils 


# revision identifiers, used by Alembic.
revision = 'b137cd5b718d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
